// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wheesper.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Wheesper {

  /// <summary>Holder for reflection information generated from wheesper.proto</summary>
  public static partial class WheesperReflection {

    #region Descriptor
    /// <summary>File descriptor for wheesper.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WheesperReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg53aGVlc3Blci5wcm90bxIId2hlZXNwZXIaC2xvZ2luLnByb3RvGgpjaGF0",
            "LnByb3RvGg1jb250YWN0LnByb3RvIqsGCghXaGVlc3BlchILCgNzZXEYASAB",
            "KAUSLQoNc2lnbm9uUmVxdWVzdBgDIAEoCzIULmxvZ2luLlNpZ25pblJlcXVl",
            "c3RIABIvCg5zaWdub25SZXNwb25zZRgEIAEoCzIVLmxvZ2luLlNpZ25vblJl",
            "c3BvbnNlSAASLwoOc2lnbm91dFJlcXVlc3QYByABKAsyFS5sb2dpbi5TaWdu",
            "b3V0UmVxdWVzZUgAEjUKEXNpZ251cE1haWxSZXF1ZXN0GAggASgLMhgubG9n",
            "aW4uU2lnbnVwTWFpbFJlcXVlc3RIABI3ChJzaWdudXBNYWlsUmVzcG9uc2UY",
            "CSABKAsyGS5sb2dpbi5TaWdudXBNYWlsUmVzcG9uc2VIABI/ChZyZWdpc3Rl",
            "ckNhcHRjaGFSZXF1ZXN0GAogASgLMh0ubG9naW4uUmVnaXN0ZXJDYXB0Y2hh",
            "UmVxdWVzdEgAEkEKF3JlZ2lzdGVyQ2FwdGNoYVJlc3BvbnNlGAsgASgLMh4u",
            "bG9naW4uUmVnaXN0ZXJDYXB0Y2hhUmVzcG9uc2VIABI1ChFzaWdudXBJbmZv",
            "UmVxdWVzdBgMIAEoCzIYLmxvZ2luLlNpZ251cEluZm9SZXF1ZXN0SAASNwoS",
            "c2lnbnVwSW5mb1Jlc3BvbnNlGA0gASgLMhkubG9naW4uU2lnbnVwSW5mb1Jl",
            "c3BvbnNlSAASSwoccGFzc3dvcmRNb2RpZnlDYXB0Y2hhUmVxdWVzdBgOIAEo",
            "CzIjLmxvZ2luLlBhc3N3b3JkTW9kaWZ5Q2FwdGNoYVJlcXVlc3RIABJNCh1w",
            "YXNzd29yZE1vZGlmeUNhcHRjaGFSZXNwb25zZRgPIAEoCzIkLmxvZ2luLlBh",
            "c3N3b3JkTW9kaWZ5Q2FwdGNoYVJlc3BvbnNlSAASOwoUcGFzc29yZE1vZGlm",
            "eVJlcXVlc3QYECABKAsyGy5sb2dpbi5QYXNzb3JkTW9kaWZ5UmVxdWVzdEgA",
            "Ej0KFXBhc3NvcmRNb2RpZnlSZXNwb25zZRgRIAEoCzIcLmxvZ2luLlBhc3Nv",
            "cmRNb2RpZnlSZXNwb25zZUgAQgUKA21zZyILCglIZWFydGJlYXRQAFABUAJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Login.LoginReflection.Descriptor, global::Chat.ChatReflection.Descriptor, global::Contact.ContactReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Wheesper.Wheesper), global::Wheesper.Wheesper.Parser, new[]{ "Seq", "SignonRequest", "SignonResponse", "SignoutRequest", "SignupMailRequest", "SignupMailResponse", "RegisterCaptchaRequest", "RegisterCaptchaResponse", "SignupInfoRequest", "SignupInfoResponse", "PasswordModifyCaptchaRequest", "PasswordModifyCaptchaResponse", "PassordModifyRequest", "PassordModifyResponse" }, new[]{ "Msg" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Wheesper.Heartbeat), global::Wheesper.Heartbeat.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Wheesper : pb::IMessage<Wheesper> {
    private static readonly pb::MessageParser<Wheesper> _parser = new pb::MessageParser<Wheesper>(() => new Wheesper());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Wheesper> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Wheesper.WheesperReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wheesper() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wheesper(Wheesper other) : this() {
      seq_ = other.seq_;
      switch (other.MsgCase) {
        case MsgOneofCase.SignonRequest:
          SignonRequest = other.SignonRequest.Clone();
          break;
        case MsgOneofCase.SignonResponse:
          SignonResponse = other.SignonResponse.Clone();
          break;
        case MsgOneofCase.SignoutRequest:
          SignoutRequest = other.SignoutRequest.Clone();
          break;
        case MsgOneofCase.SignupMailRequest:
          SignupMailRequest = other.SignupMailRequest.Clone();
          break;
        case MsgOneofCase.SignupMailResponse:
          SignupMailResponse = other.SignupMailResponse.Clone();
          break;
        case MsgOneofCase.RegisterCaptchaRequest:
          RegisterCaptchaRequest = other.RegisterCaptchaRequest.Clone();
          break;
        case MsgOneofCase.RegisterCaptchaResponse:
          RegisterCaptchaResponse = other.RegisterCaptchaResponse.Clone();
          break;
        case MsgOneofCase.SignupInfoRequest:
          SignupInfoRequest = other.SignupInfoRequest.Clone();
          break;
        case MsgOneofCase.SignupInfoResponse:
          SignupInfoResponse = other.SignupInfoResponse.Clone();
          break;
        case MsgOneofCase.PasswordModifyCaptchaRequest:
          PasswordModifyCaptchaRequest = other.PasswordModifyCaptchaRequest.Clone();
          break;
        case MsgOneofCase.PasswordModifyCaptchaResponse:
          PasswordModifyCaptchaResponse = other.PasswordModifyCaptchaResponse.Clone();
          break;
        case MsgOneofCase.PassordModifyRequest:
          PassordModifyRequest = other.PassordModifyRequest.Clone();
          break;
        case MsgOneofCase.PassordModifyResponse:
          PassordModifyResponse = other.PassordModifyResponse.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Wheesper Clone() {
      return new Wheesper(this);
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 1;
    private int seq_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "signonRequest" field.</summary>
    public const int SignonRequestFieldNumber = 3;
    /// <summary>
    /// module: login
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SigninRequest SignonRequest {
      get { return msgCase_ == MsgOneofCase.SignonRequest ? (global::Login.SigninRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignonRequest;
      }
    }

    /// <summary>Field number for the "signonResponse" field.</summary>
    public const int SignonResponseFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignonResponse SignonResponse {
      get { return msgCase_ == MsgOneofCase.SignonResponse ? (global::Login.SignonResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignonResponse;
      }
    }

    /// <summary>Field number for the "signoutRequest" field.</summary>
    public const int SignoutRequestFieldNumber = 7;
    /// <summary>
    /// Version_requset version_request = 5;
    /// Version_respense Version_respense = 6;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignoutRequese SignoutRequest {
      get { return msgCase_ == MsgOneofCase.SignoutRequest ? (global::Login.SignoutRequese) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignoutRequest;
      }
    }

    /// <summary>Field number for the "signupMailRequest" field.</summary>
    public const int SignupMailRequestFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignupMailRequest SignupMailRequest {
      get { return msgCase_ == MsgOneofCase.SignupMailRequest ? (global::Login.SignupMailRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupMailRequest;
      }
    }

    /// <summary>Field number for the "signupMailResponse" field.</summary>
    public const int SignupMailResponseFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignupMailResponse SignupMailResponse {
      get { return msgCase_ == MsgOneofCase.SignupMailResponse ? (global::Login.SignupMailResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupMailResponse;
      }
    }

    /// <summary>Field number for the "registerCaptchaRequest" field.</summary>
    public const int RegisterCaptchaRequestFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.RegisterCaptchaRequest RegisterCaptchaRequest {
      get { return msgCase_ == MsgOneofCase.RegisterCaptchaRequest ? (global::Login.RegisterCaptchaRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.RegisterCaptchaRequest;
      }
    }

    /// <summary>Field number for the "registerCaptchaResponse" field.</summary>
    public const int RegisterCaptchaResponseFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.RegisterCaptchaResponse RegisterCaptchaResponse {
      get { return msgCase_ == MsgOneofCase.RegisterCaptchaResponse ? (global::Login.RegisterCaptchaResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.RegisterCaptchaResponse;
      }
    }

    /// <summary>Field number for the "signupInfoRequest" field.</summary>
    public const int SignupInfoRequestFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignupInfoRequest SignupInfoRequest {
      get { return msgCase_ == MsgOneofCase.SignupInfoRequest ? (global::Login.SignupInfoRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupInfoRequest;
      }
    }

    /// <summary>Field number for the "signupInfoResponse" field.</summary>
    public const int SignupInfoResponseFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.SignupInfoResponse SignupInfoResponse {
      get { return msgCase_ == MsgOneofCase.SignupInfoResponse ? (global::Login.SignupInfoResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupInfoResponse;
      }
    }

    /// <summary>Field number for the "passwordModifyCaptchaRequest" field.</summary>
    public const int PasswordModifyCaptchaRequestFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.PasswordModifyCaptchaRequest PasswordModifyCaptchaRequest {
      get { return msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest ? (global::Login.PasswordModifyCaptchaRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PasswordModifyCaptchaRequest;
      }
    }

    /// <summary>Field number for the "passwordModifyCaptchaResponse" field.</summary>
    public const int PasswordModifyCaptchaResponseFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.PasswordModifyCaptchaResponse PasswordModifyCaptchaResponse {
      get { return msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse ? (global::Login.PasswordModifyCaptchaResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PasswordModifyCaptchaResponse;
      }
    }

    /// <summary>Field number for the "passordModifyRequest" field.</summary>
    public const int PassordModifyRequestFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.PassordModifyRequest PassordModifyRequest {
      get { return msgCase_ == MsgOneofCase.PassordModifyRequest ? (global::Login.PassordModifyRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PassordModifyRequest;
      }
    }

    /// <summary>Field number for the "passordModifyResponse" field.</summary>
    public const int PassordModifyResponseFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Login.PassordModifyResponse PassordModifyResponse {
      get { return msgCase_ == MsgOneofCase.PassordModifyResponse ? (global::Login.PassordModifyResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PassordModifyResponse;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      SignonRequest = 3,
      SignonResponse = 4,
      SignoutRequest = 7,
      SignupMailRequest = 8,
      SignupMailResponse = 9,
      RegisterCaptchaRequest = 10,
      RegisterCaptchaResponse = 11,
      SignupInfoRequest = 12,
      SignupInfoResponse = 13,
      PasswordModifyCaptchaRequest = 14,
      PasswordModifyCaptchaResponse = 15,
      PassordModifyRequest = 16,
      PassordModifyResponse = 17,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Wheesper);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Wheesper other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Seq != other.Seq) return false;
      if (!object.Equals(SignonRequest, other.SignonRequest)) return false;
      if (!object.Equals(SignonResponse, other.SignonResponse)) return false;
      if (!object.Equals(SignoutRequest, other.SignoutRequest)) return false;
      if (!object.Equals(SignupMailRequest, other.SignupMailRequest)) return false;
      if (!object.Equals(SignupMailResponse, other.SignupMailResponse)) return false;
      if (!object.Equals(RegisterCaptchaRequest, other.RegisterCaptchaRequest)) return false;
      if (!object.Equals(RegisterCaptchaResponse, other.RegisterCaptchaResponse)) return false;
      if (!object.Equals(SignupInfoRequest, other.SignupInfoRequest)) return false;
      if (!object.Equals(SignupInfoResponse, other.SignupInfoResponse)) return false;
      if (!object.Equals(PasswordModifyCaptchaRequest, other.PasswordModifyCaptchaRequest)) return false;
      if (!object.Equals(PasswordModifyCaptchaResponse, other.PasswordModifyCaptchaResponse)) return false;
      if (!object.Equals(PassordModifyRequest, other.PassordModifyRequest)) return false;
      if (!object.Equals(PassordModifyResponse, other.PassordModifyResponse)) return false;
      if (MsgCase != other.MsgCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignonRequest) hash ^= SignonRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignonResponse) hash ^= SignonResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignoutRequest) hash ^= SignoutRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupMailRequest) hash ^= SignupMailRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupMailResponse) hash ^= SignupMailResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.RegisterCaptchaRequest) hash ^= RegisterCaptchaRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.RegisterCaptchaResponse) hash ^= RegisterCaptchaResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) hash ^= SignupInfoRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) hash ^= SignupInfoResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) hash ^= PasswordModifyCaptchaRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) hash ^= PasswordModifyCaptchaResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) hash ^= PassordModifyRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) hash ^= PassordModifyResponse.GetHashCode();
      hash ^= (int) msgCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Seq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Seq);
      }
      if (msgCase_ == MsgOneofCase.SignonRequest) {
        output.WriteRawTag(26);
        output.WriteMessage(SignonRequest);
      }
      if (msgCase_ == MsgOneofCase.SignonResponse) {
        output.WriteRawTag(34);
        output.WriteMessage(SignonResponse);
      }
      if (msgCase_ == MsgOneofCase.SignoutRequest) {
        output.WriteRawTag(58);
        output.WriteMessage(SignoutRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailRequest) {
        output.WriteRawTag(66);
        output.WriteMessage(SignupMailRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailResponse) {
        output.WriteRawTag(74);
        output.WriteMessage(SignupMailResponse);
      }
      if (msgCase_ == MsgOneofCase.RegisterCaptchaRequest) {
        output.WriteRawTag(82);
        output.WriteMessage(RegisterCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.RegisterCaptchaResponse) {
        output.WriteRawTag(90);
        output.WriteMessage(RegisterCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
        output.WriteRawTag(98);
        output.WriteMessage(SignupInfoRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
        output.WriteRawTag(106);
        output.WriteMessage(SignupInfoResponse);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
        output.WriteRawTag(114);
        output.WriteMessage(PasswordModifyCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
        output.WriteRawTag(122);
        output.WriteMessage(PasswordModifyCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(PassordModifyRequest);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(PassordModifyResponse);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seq);
      }
      if (msgCase_ == MsgOneofCase.SignonRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignonRequest);
      }
      if (msgCase_ == MsgOneofCase.SignonResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignonResponse);
      }
      if (msgCase_ == MsgOneofCase.SignoutRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignoutRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupMailRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupMailResponse);
      }
      if (msgCase_ == MsgOneofCase.RegisterCaptchaRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RegisterCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.RegisterCaptchaResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RegisterCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupInfoRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupInfoResponse);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PasswordModifyCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PasswordModifyCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PassordModifyRequest);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PassordModifyResponse);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Wheesper other) {
      if (other == null) {
        return;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.SignonRequest:
          SignonRequest = other.SignonRequest;
          break;
        case MsgOneofCase.SignonResponse:
          SignonResponse = other.SignonResponse;
          break;
        case MsgOneofCase.SignoutRequest:
          SignoutRequest = other.SignoutRequest;
          break;
        case MsgOneofCase.SignupMailRequest:
          SignupMailRequest = other.SignupMailRequest;
          break;
        case MsgOneofCase.SignupMailResponse:
          SignupMailResponse = other.SignupMailResponse;
          break;
        case MsgOneofCase.RegisterCaptchaRequest:
          RegisterCaptchaRequest = other.RegisterCaptchaRequest;
          break;
        case MsgOneofCase.RegisterCaptchaResponse:
          RegisterCaptchaResponse = other.RegisterCaptchaResponse;
          break;
        case MsgOneofCase.SignupInfoRequest:
          SignupInfoRequest = other.SignupInfoRequest;
          break;
        case MsgOneofCase.SignupInfoResponse:
          SignupInfoResponse = other.SignupInfoResponse;
          break;
        case MsgOneofCase.PasswordModifyCaptchaRequest:
          PasswordModifyCaptchaRequest = other.PasswordModifyCaptchaRequest;
          break;
        case MsgOneofCase.PasswordModifyCaptchaResponse:
          PasswordModifyCaptchaResponse = other.PasswordModifyCaptchaResponse;
          break;
        case MsgOneofCase.PassordModifyRequest:
          PassordModifyRequest = other.PassordModifyRequest;
          break;
        case MsgOneofCase.PassordModifyResponse:
          PassordModifyResponse = other.PassordModifyResponse;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Seq = input.ReadInt32();
            break;
          }
          case 26: {
            global::Login.SigninRequest subBuilder = new global::Login.SigninRequest();
            if (msgCase_ == MsgOneofCase.SignonRequest) {
              subBuilder.MergeFrom(SignonRequest);
            }
            input.ReadMessage(subBuilder);
            SignonRequest = subBuilder;
            break;
          }
          case 34: {
            global::Login.SignonResponse subBuilder = new global::Login.SignonResponse();
            if (msgCase_ == MsgOneofCase.SignonResponse) {
              subBuilder.MergeFrom(SignonResponse);
            }
            input.ReadMessage(subBuilder);
            SignonResponse = subBuilder;
            break;
          }
          case 58: {
            global::Login.SignoutRequese subBuilder = new global::Login.SignoutRequese();
            if (msgCase_ == MsgOneofCase.SignoutRequest) {
              subBuilder.MergeFrom(SignoutRequest);
            }
            input.ReadMessage(subBuilder);
            SignoutRequest = subBuilder;
            break;
          }
          case 66: {
            global::Login.SignupMailRequest subBuilder = new global::Login.SignupMailRequest();
            if (msgCase_ == MsgOneofCase.SignupMailRequest) {
              subBuilder.MergeFrom(SignupMailRequest);
            }
            input.ReadMessage(subBuilder);
            SignupMailRequest = subBuilder;
            break;
          }
          case 74: {
            global::Login.SignupMailResponse subBuilder = new global::Login.SignupMailResponse();
            if (msgCase_ == MsgOneofCase.SignupMailResponse) {
              subBuilder.MergeFrom(SignupMailResponse);
            }
            input.ReadMessage(subBuilder);
            SignupMailResponse = subBuilder;
            break;
          }
          case 82: {
            global::Login.RegisterCaptchaRequest subBuilder = new global::Login.RegisterCaptchaRequest();
            if (msgCase_ == MsgOneofCase.RegisterCaptchaRequest) {
              subBuilder.MergeFrom(RegisterCaptchaRequest);
            }
            input.ReadMessage(subBuilder);
            RegisterCaptchaRequest = subBuilder;
            break;
          }
          case 90: {
            global::Login.RegisterCaptchaResponse subBuilder = new global::Login.RegisterCaptchaResponse();
            if (msgCase_ == MsgOneofCase.RegisterCaptchaResponse) {
              subBuilder.MergeFrom(RegisterCaptchaResponse);
            }
            input.ReadMessage(subBuilder);
            RegisterCaptchaResponse = subBuilder;
            break;
          }
          case 98: {
            global::Login.SignupInfoRequest subBuilder = new global::Login.SignupInfoRequest();
            if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
              subBuilder.MergeFrom(SignupInfoRequest);
            }
            input.ReadMessage(subBuilder);
            SignupInfoRequest = subBuilder;
            break;
          }
          case 106: {
            global::Login.SignupInfoResponse subBuilder = new global::Login.SignupInfoResponse();
            if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
              subBuilder.MergeFrom(SignupInfoResponse);
            }
            input.ReadMessage(subBuilder);
            SignupInfoResponse = subBuilder;
            break;
          }
          case 114: {
            global::Login.PasswordModifyCaptchaRequest subBuilder = new global::Login.PasswordModifyCaptchaRequest();
            if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
              subBuilder.MergeFrom(PasswordModifyCaptchaRequest);
            }
            input.ReadMessage(subBuilder);
            PasswordModifyCaptchaRequest = subBuilder;
            break;
          }
          case 122: {
            global::Login.PasswordModifyCaptchaResponse subBuilder = new global::Login.PasswordModifyCaptchaResponse();
            if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
              subBuilder.MergeFrom(PasswordModifyCaptchaResponse);
            }
            input.ReadMessage(subBuilder);
            PasswordModifyCaptchaResponse = subBuilder;
            break;
          }
          case 130: {
            global::Login.PassordModifyRequest subBuilder = new global::Login.PassordModifyRequest();
            if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
              subBuilder.MergeFrom(PassordModifyRequest);
            }
            input.ReadMessage(subBuilder);
            PassordModifyRequest = subBuilder;
            break;
          }
          case 138: {
            global::Login.PassordModifyResponse subBuilder = new global::Login.PassordModifyResponse();
            if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
              subBuilder.MergeFrom(PassordModifyResponse);
            }
            input.ReadMessage(subBuilder);
            PassordModifyResponse = subBuilder;
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 心跳包 ①客户端->服务端  ②服务端->客户端（模仿于万恶的断网客户端）
  /// </summary>
  public sealed partial class Heartbeat : pb::IMessage<Heartbeat> {
    private static readonly pb::MessageParser<Heartbeat> _parser = new pb::MessageParser<Heartbeat>(() => new Heartbeat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Heartbeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Wheesper.WheesperReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat(Heartbeat other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat Clone() {
      return new Heartbeat(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Heartbeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Heartbeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Heartbeat other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
