// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtocolBuffer {

  /// <summary>Holder for reflection information generated from ProtoMessage.proto</summary>
  public static partial class ProtoMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90b01lc3NhZ2UucHJvdG8SDlByb3RvY29sQnVmZmVyIswHCgxQcm90",
            "b01lc3NhZ2USCwoDc2VxGAEgASgFEi4KCWhlYXJ0YmVhdBgFIAEoCzIZLlBy",
            "b3RvY29sQnVmZmVyLkhlYXJ0YmVhdEgAEjYKDXNpZ25pblJlcXVlc3QYCyAB",
            "KAsyHS5Qcm90b2NvbEJ1ZmZlci5TaWduaW5SZXF1ZXN0SAASOAoOc2lnbmlu",
            "UmVzcG9uc2UYDCABKAsyHi5Qcm90b2NvbEJ1ZmZlci5TaWduaW5SZXNwb25z",
            "ZUgAEjgKDnNpZ25vdXRSZXF1ZXN0GA0gASgLMh4uUHJvdG9jb2xCdWZmZXIu",
            "U2lnbm91dFJlcXVlc3RIABI+ChFzaWdudXBNYWlsUmVxdWVzdBgOIAEoCzIh",
            "LlByb3RvY29sQnVmZmVyLlNpZ251cE1haWxSZXF1ZXN0SAASQAoSc2lnbnVw",
            "TWFpbFJlc3BvbnNlGA8gASgLMiIuUHJvdG9jb2xCdWZmZXIuU2lnbnVwTWFp",
            "bFJlc3BvbnNlSAASRAoUU2lnbnVwQ2FwdGNoYVJlcXVlc3QYECABKAsyJC5Q",
            "cm90b2NvbEJ1ZmZlci5TaWdudXBDYXB0Y2hhUmVxdWVzdEgAEkYKFVNpZ251",
            "cENhcHRjaGFSZXNwb25zZRgRIAEoCzIlLlByb3RvY29sQnVmZmVyLlNpZ251",
            "cENhcHRjaGFSZXNwb25zZUgAEj4KEXNpZ251cEluZm9SZXF1ZXN0GBIgASgL",
            "MiEuUHJvdG9jb2xCdWZmZXIuU2lnbnVwSW5mb1JlcXVlc3RIABJAChJzaWdu",
            "dXBJbmZvUmVzcG9uc2UYEyABKAsyIi5Qcm90b2NvbEJ1ZmZlci5TaWdudXBJ",
            "bmZvUmVzcG9uc2VIABJUChxwYXNzd29yZE1vZGlmeUNhcHRjaGFSZXF1ZXN0",
            "GBQgASgLMiwuUHJvdG9jb2xCdWZmZXIuUGFzc3dvcmRNb2RpZnlDYXB0Y2hh",
            "UmVxdWVzdEgAElYKHXBhc3N3b3JkTW9kaWZ5Q2FwdGNoYVJlc3BvbnNlGBUg",
            "ASgLMi0uUHJvdG9jb2xCdWZmZXIuUGFzc3dvcmRNb2RpZnlDYXB0Y2hhUmVz",
            "cG9uc2VIABJEChRwYXNzb3JkTW9kaWZ5UmVxdWVzdBgWIAEoCzIkLlByb3Rv",
            "Y29sQnVmZmVyLlBhc3NvcmRNb2RpZnlSZXF1ZXN0SAASRgoVcGFzc29yZE1v",
            "ZGlmeVJlc3BvbnNlGBcgASgLMiUuUHJvdG9jb2xCdWZmZXIuUGFzc29yZE1v",
            "ZGlmeVJlc3BvbnNlSABCBQoDbXNnIgsKCUhlYXJ0YmVhdCI3Cg1TaWduaW5S",
            "ZXF1ZXN0EhQKDG1haWxfYWRkcmVzcxgBIAEoCRIQCghwYXNzd29yZBgCIAEo",
            "CSI2Cg5TaWduaW5SZXNwb25zZRIOCgZzdGF0dXMYASABKAgSFAoMbWFpbF9h",
            "ZGRyZXNzGAIgASgJIhAKDlNpZ25vdXRSZXF1ZXN0IikKEVNpZ251cE1haWxS",
            "ZXF1ZXN0EhQKDG1haWxfYWRkcmVzcxgBIAEoCSI6ChJTaWdudXBNYWlsUmVz",
            "cG9uc2USDgoGc3RhdHVzGAEgASgIEhQKDG1haWxfYWRkcmVzcxgCIAEoCSIs",
            "ChRTaWdudXBDYXB0Y2hhUmVxdWVzdBIUCgxtYWlsX2FkZHJlc3MYASABKAki",
            "PQoVU2lnbnVwQ2FwdGNoYVJlc3BvbnNlEg4KBnN0YXR1cxgBIAEoCBIUCgxt",
            "YWlsX2FkZHJlc3MYAiABKAkiXgoRU2lnbnVwSW5mb1JlcXVlc3QSFAoMbWFp",
            "bF9hZGRyZXNzGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhAKCG5pY2tuYW1l",
            "GAMgASgJEg8KB2NhcHRjaGEYBCABKAkiOgoSU2lnbnVwSW5mb1Jlc3BvbnNl",
            "Eg4KBnN0YXR1cxgBIAEoCBIUCgxtYWlsX2FkZHJlc3MYAiABKAkiNAocUGFz",
            "c3dvcmRNb2RpZnlDYXB0Y2hhUmVxdWVzdBIUCgxtYWlsX2FkZHJlc3MYASAB",
            "KAkiRQodUGFzc3dvcmRNb2RpZnlDYXB0Y2hhUmVzcG9uc2USDgoGc3RhdHVz",
            "GAEgASgIEhQKDG1haWxfYWRkcmVzcxgCIAEoCSJPChRQYXNzb3JkTW9kaWZ5",
            "UmVxdWVzdBIUCgxtYWlsX2FkZHJlc3MYASABKAkSDwoHY2FwdGNoYRgCIAEo",
            "CRIQCghwYXNzd29yZBgDIAEoCSI9ChVQYXNzb3JkTW9kaWZ5UmVzcG9uc2US",
            "DgoGc3RhdHVzGAEgASgIEhQKDG1haWxfYWRkcmVzcxgCIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.ProtoMessage), global::ProtocolBuffer.ProtoMessage.Parser, new[]{ "Seq", "Heartbeat", "SigninRequest", "SigninResponse", "SignoutRequest", "SignupMailRequest", "SignupMailResponse", "SignupCaptchaRequest", "SignupCaptchaResponse", "SignupInfoRequest", "SignupInfoResponse", "PasswordModifyCaptchaRequest", "PasswordModifyCaptchaResponse", "PassordModifyRequest", "PassordModifyResponse" }, new[]{ "Msg" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.Heartbeat), global::ProtocolBuffer.Heartbeat.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SigninRequest), global::ProtocolBuffer.SigninRequest.Parser, new[]{ "MailAddress", "Password" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SigninResponse), global::ProtocolBuffer.SigninResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignoutRequest), global::ProtocolBuffer.SignoutRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupMailRequest), global::ProtocolBuffer.SignupMailRequest.Parser, new[]{ "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupMailResponse), global::ProtocolBuffer.SignupMailResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupCaptchaRequest), global::ProtocolBuffer.SignupCaptchaRequest.Parser, new[]{ "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupCaptchaResponse), global::ProtocolBuffer.SignupCaptchaResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupInfoRequest), global::ProtocolBuffer.SignupInfoRequest.Parser, new[]{ "MailAddress", "Password", "Nickname", "Captcha" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.SignupInfoResponse), global::ProtocolBuffer.SignupInfoResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.PasswordModifyCaptchaRequest), global::ProtocolBuffer.PasswordModifyCaptchaRequest.Parser, new[]{ "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.PasswordModifyCaptchaResponse), global::ProtocolBuffer.PasswordModifyCaptchaResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.PassordModifyRequest), global::ProtocolBuffer.PassordModifyRequest.Parser, new[]{ "MailAddress", "Captcha", "Password" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocolBuffer.PassordModifyResponse), global::ProtocolBuffer.PassordModifyResponse.Parser, new[]{ "Status", "MailAddress" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// special type range:        1  - 10
  /// login module type range:   11 - 40
  /// chat module type range:    41 - 70
  /// contact module type range: 71 - 100
  /// </summary>
  public sealed partial class ProtoMessage : pb::IMessage<ProtoMessage> {
    private static readonly pb::MessageParser<ProtoMessage> _parser = new pb::MessageParser<ProtoMessage>(() => new ProtoMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtoMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoMessage(ProtoMessage other) : this() {
      seq_ = other.seq_;
      switch (other.MsgCase) {
        case MsgOneofCase.Heartbeat:
          Heartbeat = other.Heartbeat.Clone();
          break;
        case MsgOneofCase.SigninRequest:
          SigninRequest = other.SigninRequest.Clone();
          break;
        case MsgOneofCase.SigninResponse:
          SigninResponse = other.SigninResponse.Clone();
          break;
        case MsgOneofCase.SignoutRequest:
          SignoutRequest = other.SignoutRequest.Clone();
          break;
        case MsgOneofCase.SignupMailRequest:
          SignupMailRequest = other.SignupMailRequest.Clone();
          break;
        case MsgOneofCase.SignupMailResponse:
          SignupMailResponse = other.SignupMailResponse.Clone();
          break;
        case MsgOneofCase.SignupCaptchaRequest:
          SignupCaptchaRequest = other.SignupCaptchaRequest.Clone();
          break;
        case MsgOneofCase.SignupCaptchaResponse:
          SignupCaptchaResponse = other.SignupCaptchaResponse.Clone();
          break;
        case MsgOneofCase.SignupInfoRequest:
          SignupInfoRequest = other.SignupInfoRequest.Clone();
          break;
        case MsgOneofCase.SignupInfoResponse:
          SignupInfoResponse = other.SignupInfoResponse.Clone();
          break;
        case MsgOneofCase.PasswordModifyCaptchaRequest:
          PasswordModifyCaptchaRequest = other.PasswordModifyCaptchaRequest.Clone();
          break;
        case MsgOneofCase.PasswordModifyCaptchaResponse:
          PasswordModifyCaptchaResponse = other.PasswordModifyCaptchaResponse.Clone();
          break;
        case MsgOneofCase.PassordModifyRequest:
          PassordModifyRequest = other.PassordModifyRequest.Clone();
          break;
        case MsgOneofCase.PassordModifyResponse:
          PassordModifyResponse = other.PassordModifyResponse.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoMessage Clone() {
      return new ProtoMessage(this);
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 1;
    private int seq_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "heartbeat" field.</summary>
    public const int HeartbeatFieldNumber = 5;
    /// <summary>
    /// special type:
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.Heartbeat Heartbeat {
      get { return msgCase_ == MsgOneofCase.Heartbeat ? (global::ProtocolBuffer.Heartbeat) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Heartbeat;
      }
    }

    /// <summary>Field number for the "signinRequest" field.</summary>
    public const int SigninRequestFieldNumber = 11;
    /// <summary>
    /// module: login
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SigninRequest SigninRequest {
      get { return msgCase_ == MsgOneofCase.SigninRequest ? (global::ProtocolBuffer.SigninRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SigninRequest;
      }
    }

    /// <summary>Field number for the "signinResponse" field.</summary>
    public const int SigninResponseFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SigninResponse SigninResponse {
      get { return msgCase_ == MsgOneofCase.SigninResponse ? (global::ProtocolBuffer.SigninResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SigninResponse;
      }
    }

    /// <summary>Field number for the "signoutRequest" field.</summary>
    public const int SignoutRequestFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignoutRequest SignoutRequest {
      get { return msgCase_ == MsgOneofCase.SignoutRequest ? (global::ProtocolBuffer.SignoutRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignoutRequest;
      }
    }

    /// <summary>Field number for the "signupMailRequest" field.</summary>
    public const int SignupMailRequestFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupMailRequest SignupMailRequest {
      get { return msgCase_ == MsgOneofCase.SignupMailRequest ? (global::ProtocolBuffer.SignupMailRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupMailRequest;
      }
    }

    /// <summary>Field number for the "signupMailResponse" field.</summary>
    public const int SignupMailResponseFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupMailResponse SignupMailResponse {
      get { return msgCase_ == MsgOneofCase.SignupMailResponse ? (global::ProtocolBuffer.SignupMailResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupMailResponse;
      }
    }

    /// <summary>Field number for the "SignupCaptchaRequest" field.</summary>
    public const int SignupCaptchaRequestFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupCaptchaRequest SignupCaptchaRequest {
      get { return msgCase_ == MsgOneofCase.SignupCaptchaRequest ? (global::ProtocolBuffer.SignupCaptchaRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupCaptchaRequest;
      }
    }

    /// <summary>Field number for the "SignupCaptchaResponse" field.</summary>
    public const int SignupCaptchaResponseFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupCaptchaResponse SignupCaptchaResponse {
      get { return msgCase_ == MsgOneofCase.SignupCaptchaResponse ? (global::ProtocolBuffer.SignupCaptchaResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupCaptchaResponse;
      }
    }

    /// <summary>Field number for the "signupInfoRequest" field.</summary>
    public const int SignupInfoRequestFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupInfoRequest SignupInfoRequest {
      get { return msgCase_ == MsgOneofCase.SignupInfoRequest ? (global::ProtocolBuffer.SignupInfoRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupInfoRequest;
      }
    }

    /// <summary>Field number for the "signupInfoResponse" field.</summary>
    public const int SignupInfoResponseFieldNumber = 19;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.SignupInfoResponse SignupInfoResponse {
      get { return msgCase_ == MsgOneofCase.SignupInfoResponse ? (global::ProtocolBuffer.SignupInfoResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.SignupInfoResponse;
      }
    }

    /// <summary>Field number for the "passwordModifyCaptchaRequest" field.</summary>
    public const int PasswordModifyCaptchaRequestFieldNumber = 20;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.PasswordModifyCaptchaRequest PasswordModifyCaptchaRequest {
      get { return msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest ? (global::ProtocolBuffer.PasswordModifyCaptchaRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PasswordModifyCaptchaRequest;
      }
    }

    /// <summary>Field number for the "passwordModifyCaptchaResponse" field.</summary>
    public const int PasswordModifyCaptchaResponseFieldNumber = 21;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.PasswordModifyCaptchaResponse PasswordModifyCaptchaResponse {
      get { return msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse ? (global::ProtocolBuffer.PasswordModifyCaptchaResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PasswordModifyCaptchaResponse;
      }
    }

    /// <summary>Field number for the "passordModifyRequest" field.</summary>
    public const int PassordModifyRequestFieldNumber = 22;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.PassordModifyRequest PassordModifyRequest {
      get { return msgCase_ == MsgOneofCase.PassordModifyRequest ? (global::ProtocolBuffer.PassordModifyRequest) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PassordModifyRequest;
      }
    }

    /// <summary>Field number for the "passordModifyResponse" field.</summary>
    public const int PassordModifyResponseFieldNumber = 23;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtocolBuffer.PassordModifyResponse PassordModifyResponse {
      get { return msgCase_ == MsgOneofCase.PassordModifyResponse ? (global::ProtocolBuffer.PassordModifyResponse) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.PassordModifyResponse;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      Heartbeat = 5,
      SigninRequest = 11,
      SigninResponse = 12,
      SignoutRequest = 13,
      SignupMailRequest = 14,
      SignupMailResponse = 15,
      SignupCaptchaRequest = 16,
      SignupCaptchaResponse = 17,
      SignupInfoRequest = 18,
      SignupInfoResponse = 19,
      PasswordModifyCaptchaRequest = 20,
      PasswordModifyCaptchaResponse = 21,
      PassordModifyRequest = 22,
      PassordModifyResponse = 23,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtoMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtoMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Seq != other.Seq) return false;
      if (!object.Equals(Heartbeat, other.Heartbeat)) return false;
      if (!object.Equals(SigninRequest, other.SigninRequest)) return false;
      if (!object.Equals(SigninResponse, other.SigninResponse)) return false;
      if (!object.Equals(SignoutRequest, other.SignoutRequest)) return false;
      if (!object.Equals(SignupMailRequest, other.SignupMailRequest)) return false;
      if (!object.Equals(SignupMailResponse, other.SignupMailResponse)) return false;
      if (!object.Equals(SignupCaptchaRequest, other.SignupCaptchaRequest)) return false;
      if (!object.Equals(SignupCaptchaResponse, other.SignupCaptchaResponse)) return false;
      if (!object.Equals(SignupInfoRequest, other.SignupInfoRequest)) return false;
      if (!object.Equals(SignupInfoResponse, other.SignupInfoResponse)) return false;
      if (!object.Equals(PasswordModifyCaptchaRequest, other.PasswordModifyCaptchaRequest)) return false;
      if (!object.Equals(PasswordModifyCaptchaResponse, other.PasswordModifyCaptchaResponse)) return false;
      if (!object.Equals(PassordModifyRequest, other.PassordModifyRequest)) return false;
      if (!object.Equals(PassordModifyResponse, other.PassordModifyResponse)) return false;
      if (MsgCase != other.MsgCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (msgCase_ == MsgOneofCase.Heartbeat) hash ^= Heartbeat.GetHashCode();
      if (msgCase_ == MsgOneofCase.SigninRequest) hash ^= SigninRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SigninResponse) hash ^= SigninResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignoutRequest) hash ^= SignoutRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupMailRequest) hash ^= SignupMailRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupMailResponse) hash ^= SignupMailResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupCaptchaRequest) hash ^= SignupCaptchaRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupCaptchaResponse) hash ^= SignupCaptchaResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) hash ^= SignupInfoRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) hash ^= SignupInfoResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) hash ^= PasswordModifyCaptchaRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) hash ^= PasswordModifyCaptchaResponse.GetHashCode();
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) hash ^= PassordModifyRequest.GetHashCode();
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) hash ^= PassordModifyResponse.GetHashCode();
      hash ^= (int) msgCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Seq != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Seq);
      }
      if (msgCase_ == MsgOneofCase.Heartbeat) {
        output.WriteRawTag(42);
        output.WriteMessage(Heartbeat);
      }
      if (msgCase_ == MsgOneofCase.SigninRequest) {
        output.WriteRawTag(90);
        output.WriteMessage(SigninRequest);
      }
      if (msgCase_ == MsgOneofCase.SigninResponse) {
        output.WriteRawTag(98);
        output.WriteMessage(SigninResponse);
      }
      if (msgCase_ == MsgOneofCase.SignoutRequest) {
        output.WriteRawTag(106);
        output.WriteMessage(SignoutRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailRequest) {
        output.WriteRawTag(114);
        output.WriteMessage(SignupMailRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailResponse) {
        output.WriteRawTag(122);
        output.WriteMessage(SignupMailResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupCaptchaRequest) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(SignupCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupCaptchaResponse) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(SignupCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(SignupInfoRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(SignupInfoResponse);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(PasswordModifyCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(PasswordModifyCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(PassordModifyRequest);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(PassordModifyResponse);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seq);
      }
      if (msgCase_ == MsgOneofCase.Heartbeat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Heartbeat);
      }
      if (msgCase_ == MsgOneofCase.SigninRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SigninRequest);
      }
      if (msgCase_ == MsgOneofCase.SigninResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SigninResponse);
      }
      if (msgCase_ == MsgOneofCase.SignoutRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignoutRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupMailRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupMailResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignupMailResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupCaptchaRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SignupCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupCaptchaResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SignupCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SignupInfoRequest);
      }
      if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SignupInfoResponse);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PasswordModifyCaptchaRequest);
      }
      if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PasswordModifyCaptchaResponse);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PassordModifyRequest);
      }
      if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PassordModifyResponse);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtoMessage other) {
      if (other == null) {
        return;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.Heartbeat:
          Heartbeat = other.Heartbeat;
          break;
        case MsgOneofCase.SigninRequest:
          SigninRequest = other.SigninRequest;
          break;
        case MsgOneofCase.SigninResponse:
          SigninResponse = other.SigninResponse;
          break;
        case MsgOneofCase.SignoutRequest:
          SignoutRequest = other.SignoutRequest;
          break;
        case MsgOneofCase.SignupMailRequest:
          SignupMailRequest = other.SignupMailRequest;
          break;
        case MsgOneofCase.SignupMailResponse:
          SignupMailResponse = other.SignupMailResponse;
          break;
        case MsgOneofCase.SignupCaptchaRequest:
          SignupCaptchaRequest = other.SignupCaptchaRequest;
          break;
        case MsgOneofCase.SignupCaptchaResponse:
          SignupCaptchaResponse = other.SignupCaptchaResponse;
          break;
        case MsgOneofCase.SignupInfoRequest:
          SignupInfoRequest = other.SignupInfoRequest;
          break;
        case MsgOneofCase.SignupInfoResponse:
          SignupInfoResponse = other.SignupInfoResponse;
          break;
        case MsgOneofCase.PasswordModifyCaptchaRequest:
          PasswordModifyCaptchaRequest = other.PasswordModifyCaptchaRequest;
          break;
        case MsgOneofCase.PasswordModifyCaptchaResponse:
          PasswordModifyCaptchaResponse = other.PasswordModifyCaptchaResponse;
          break;
        case MsgOneofCase.PassordModifyRequest:
          PassordModifyRequest = other.PassordModifyRequest;
          break;
        case MsgOneofCase.PassordModifyResponse:
          PassordModifyResponse = other.PassordModifyResponse;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Seq = input.ReadInt32();
            break;
          }
          case 42: {
            global::ProtocolBuffer.Heartbeat subBuilder = new global::ProtocolBuffer.Heartbeat();
            if (msgCase_ == MsgOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 90: {
            global::ProtocolBuffer.SigninRequest subBuilder = new global::ProtocolBuffer.SigninRequest();
            if (msgCase_ == MsgOneofCase.SigninRequest) {
              subBuilder.MergeFrom(SigninRequest);
            }
            input.ReadMessage(subBuilder);
            SigninRequest = subBuilder;
            break;
          }
          case 98: {
            global::ProtocolBuffer.SigninResponse subBuilder = new global::ProtocolBuffer.SigninResponse();
            if (msgCase_ == MsgOneofCase.SigninResponse) {
              subBuilder.MergeFrom(SigninResponse);
            }
            input.ReadMessage(subBuilder);
            SigninResponse = subBuilder;
            break;
          }
          case 106: {
            global::ProtocolBuffer.SignoutRequest subBuilder = new global::ProtocolBuffer.SignoutRequest();
            if (msgCase_ == MsgOneofCase.SignoutRequest) {
              subBuilder.MergeFrom(SignoutRequest);
            }
            input.ReadMessage(subBuilder);
            SignoutRequest = subBuilder;
            break;
          }
          case 114: {
            global::ProtocolBuffer.SignupMailRequest subBuilder = new global::ProtocolBuffer.SignupMailRequest();
            if (msgCase_ == MsgOneofCase.SignupMailRequest) {
              subBuilder.MergeFrom(SignupMailRequest);
            }
            input.ReadMessage(subBuilder);
            SignupMailRequest = subBuilder;
            break;
          }
          case 122: {
            global::ProtocolBuffer.SignupMailResponse subBuilder = new global::ProtocolBuffer.SignupMailResponse();
            if (msgCase_ == MsgOneofCase.SignupMailResponse) {
              subBuilder.MergeFrom(SignupMailResponse);
            }
            input.ReadMessage(subBuilder);
            SignupMailResponse = subBuilder;
            break;
          }
          case 130: {
            global::ProtocolBuffer.SignupCaptchaRequest subBuilder = new global::ProtocolBuffer.SignupCaptchaRequest();
            if (msgCase_ == MsgOneofCase.SignupCaptchaRequest) {
              subBuilder.MergeFrom(SignupCaptchaRequest);
            }
            input.ReadMessage(subBuilder);
            SignupCaptchaRequest = subBuilder;
            break;
          }
          case 138: {
            global::ProtocolBuffer.SignupCaptchaResponse subBuilder = new global::ProtocolBuffer.SignupCaptchaResponse();
            if (msgCase_ == MsgOneofCase.SignupCaptchaResponse) {
              subBuilder.MergeFrom(SignupCaptchaResponse);
            }
            input.ReadMessage(subBuilder);
            SignupCaptchaResponse = subBuilder;
            break;
          }
          case 146: {
            global::ProtocolBuffer.SignupInfoRequest subBuilder = new global::ProtocolBuffer.SignupInfoRequest();
            if (msgCase_ == MsgOneofCase.SignupInfoRequest) {
              subBuilder.MergeFrom(SignupInfoRequest);
            }
            input.ReadMessage(subBuilder);
            SignupInfoRequest = subBuilder;
            break;
          }
          case 154: {
            global::ProtocolBuffer.SignupInfoResponse subBuilder = new global::ProtocolBuffer.SignupInfoResponse();
            if (msgCase_ == MsgOneofCase.SignupInfoResponse) {
              subBuilder.MergeFrom(SignupInfoResponse);
            }
            input.ReadMessage(subBuilder);
            SignupInfoResponse = subBuilder;
            break;
          }
          case 162: {
            global::ProtocolBuffer.PasswordModifyCaptchaRequest subBuilder = new global::ProtocolBuffer.PasswordModifyCaptchaRequest();
            if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaRequest) {
              subBuilder.MergeFrom(PasswordModifyCaptchaRequest);
            }
            input.ReadMessage(subBuilder);
            PasswordModifyCaptchaRequest = subBuilder;
            break;
          }
          case 170: {
            global::ProtocolBuffer.PasswordModifyCaptchaResponse subBuilder = new global::ProtocolBuffer.PasswordModifyCaptchaResponse();
            if (msgCase_ == MsgOneofCase.PasswordModifyCaptchaResponse) {
              subBuilder.MergeFrom(PasswordModifyCaptchaResponse);
            }
            input.ReadMessage(subBuilder);
            PasswordModifyCaptchaResponse = subBuilder;
            break;
          }
          case 178: {
            global::ProtocolBuffer.PassordModifyRequest subBuilder = new global::ProtocolBuffer.PassordModifyRequest();
            if (msgCase_ == MsgOneofCase.PassordModifyRequest) {
              subBuilder.MergeFrom(PassordModifyRequest);
            }
            input.ReadMessage(subBuilder);
            PassordModifyRequest = subBuilder;
            break;
          }
          case 186: {
            global::ProtocolBuffer.PassordModifyResponse subBuilder = new global::ProtocolBuffer.PassordModifyResponse();
            if (msgCase_ == MsgOneofCase.PassordModifyResponse) {
              subBuilder.MergeFrom(PassordModifyResponse);
            }
            input.ReadMessage(subBuilder);
            PassordModifyResponse = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class Heartbeat : pb::IMessage<Heartbeat> {
    private static readonly pb::MessageParser<Heartbeat> _parser = new pb::MessageParser<Heartbeat>(() => new Heartbeat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Heartbeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat(Heartbeat other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat Clone() {
      return new Heartbeat(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Heartbeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Heartbeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Heartbeat other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  /// func: sign in
  /// </summary>
  public sealed partial class SigninRequest : pb::IMessage<SigninRequest> {
    private static readonly pb::MessageParser<SigninRequest> _parser = new pb::MessageParser<SigninRequest>(() => new SigninRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SigninRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninRequest(SigninRequest other) : this() {
      mailAddress_ = other.mailAddress_;
      password_ = other.password_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninRequest Clone() {
      return new SigninRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SigninRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SigninRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      if (Password != other.Password) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SigninRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SigninResponse : pb::IMessage<SigninResponse> {
    private static readonly pb::MessageParser<SigninResponse> _parser = new pb::MessageParser<SigninResponse>(() => new SigninResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SigninResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninResponse(SigninResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SigninResponse Clone() {
      return new SigninResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SigninResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SigninResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SigninResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// func: sign out
  /// ①注销包（客户端->服务端，服务端接受到这个包，表示客户端主动登出，将为该用户执行登出操作，但并不释放连接，客户端也保证用户登出）
  /// </summary>
  public sealed partial class SignoutRequest : pb::IMessage<SignoutRequest> {
    private static readonly pb::MessageParser<SignoutRequest> _parser = new pb::MessageParser<SignoutRequest>(() => new SignoutRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignoutRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignoutRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignoutRequest(SignoutRequest other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignoutRequest Clone() {
      return new SignoutRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignoutRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignoutRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignoutRequest other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  /// func: sign up
  /// </summary>
  public sealed partial class SignupMailRequest : pb::IMessage<SignupMailRequest> {
    private static readonly pb::MessageParser<SignupMailRequest> _parser = new pb::MessageParser<SignupMailRequest>(() => new SignupMailRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupMailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailRequest(SignupMailRequest other) : this() {
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailRequest Clone() {
      return new SignupMailRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupMailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupMailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupMailRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignupMailResponse : pb::IMessage<SignupMailResponse> {
    private static readonly pb::MessageParser<SignupMailResponse> _parser = new pb::MessageParser<SignupMailResponse>(() => new SignupMailResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupMailResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailResponse(SignupMailResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupMailResponse Clone() {
      return new SignupMailResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupMailResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupMailResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupMailResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignupCaptchaRequest : pb::IMessage<SignupCaptchaRequest> {
    private static readonly pb::MessageParser<SignupCaptchaRequest> _parser = new pb::MessageParser<SignupCaptchaRequest>(() => new SignupCaptchaRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupCaptchaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaRequest(SignupCaptchaRequest other) : this() {
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaRequest Clone() {
      return new SignupCaptchaRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupCaptchaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupCaptchaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupCaptchaRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignupCaptchaResponse : pb::IMessage<SignupCaptchaResponse> {
    private static readonly pb::MessageParser<SignupCaptchaResponse> _parser = new pb::MessageParser<SignupCaptchaResponse>(() => new SignupCaptchaResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupCaptchaResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaResponse(SignupCaptchaResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupCaptchaResponse Clone() {
      return new SignupCaptchaResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    /// <summary>
    ///验证码是否发送成功
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupCaptchaResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupCaptchaResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupCaptchaResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignupInfoRequest : pb::IMessage<SignupInfoRequest> {
    private static readonly pb::MessageParser<SignupInfoRequest> _parser = new pb::MessageParser<SignupInfoRequest>(() => new SignupInfoRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoRequest(SignupInfoRequest other) : this() {
      mailAddress_ = other.mailAddress_;
      password_ = other.password_;
      nickname_ = other.nickname_;
      captcha_ = other.captcha_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoRequest Clone() {
      return new SignupInfoRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickname" field.</summary>
    public const int NicknameFieldNumber = 3;
    private string nickname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nickname {
      get { return nickname_; }
      set {
        nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "captcha" field.</summary>
    public const int CaptchaFieldNumber = 4;
    private string captcha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Captcha {
      get { return captcha_; }
      set {
        captcha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      if (Password != other.Password) return false;
      if (Nickname != other.Nickname) return false;
      if (Captcha != other.Captcha) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
      if (Captcha.Length != 0) hash ^= Captcha.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nickname);
      }
      if (Captcha.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Captcha);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Nickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
      }
      if (Captcha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Captcha);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupInfoRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Nickname.Length != 0) {
        Nickname = other.Nickname;
      }
      if (other.Captcha.Length != 0) {
        Captcha = other.Captcha;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            Nickname = input.ReadString();
            break;
          }
          case 34: {
            Captcha = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignupInfoResponse : pb::IMessage<SignupInfoResponse> {
    private static readonly pb::MessageParser<SignupInfoResponse> _parser = new pb::MessageParser<SignupInfoResponse>(() => new SignupInfoResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignupInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoResponse(SignupInfoResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignupInfoResponse Clone() {
      return new SignupInfoResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignupInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignupInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignupInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PasswordModifyCaptchaRequest : pb::IMessage<PasswordModifyCaptchaRequest> {
    private static readonly pb::MessageParser<PasswordModifyCaptchaRequest> _parser = new pb::MessageParser<PasswordModifyCaptchaRequest>(() => new PasswordModifyCaptchaRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PasswordModifyCaptchaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaRequest(PasswordModifyCaptchaRequest other) : this() {
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaRequest Clone() {
      return new PasswordModifyCaptchaRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PasswordModifyCaptchaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PasswordModifyCaptchaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PasswordModifyCaptchaRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PasswordModifyCaptchaResponse : pb::IMessage<PasswordModifyCaptchaResponse> {
    private static readonly pb::MessageParser<PasswordModifyCaptchaResponse> _parser = new pb::MessageParser<PasswordModifyCaptchaResponse>(() => new PasswordModifyCaptchaResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PasswordModifyCaptchaResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaResponse(PasswordModifyCaptchaResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PasswordModifyCaptchaResponse Clone() {
      return new PasswordModifyCaptchaResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PasswordModifyCaptchaResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PasswordModifyCaptchaResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PasswordModifyCaptchaResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PassordModifyRequest : pb::IMessage<PassordModifyRequest> {
    private static readonly pb::MessageParser<PassordModifyRequest> _parser = new pb::MessageParser<PassordModifyRequest>(() => new PassordModifyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PassordModifyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyRequest(PassordModifyRequest other) : this() {
      mailAddress_ = other.mailAddress_;
      captcha_ = other.captcha_;
      password_ = other.password_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyRequest Clone() {
      return new PassordModifyRequest(this);
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 1;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "captcha" field.</summary>
    public const int CaptchaFieldNumber = 2;
    private string captcha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Captcha {
      get { return captcha_; }
      set {
        captcha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PassordModifyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PassordModifyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailAddress != other.MailAddress) return false;
      if (Captcha != other.Captcha) return false;
      if (Password != other.Password) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      if (Captcha.Length != 0) hash ^= Captcha.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MailAddress);
      }
      if (Captcha.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Captcha);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      if (Captcha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Captcha);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PassordModifyRequest other) {
      if (other == null) {
        return;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
      if (other.Captcha.Length != 0) {
        Captcha = other.Captcha;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MailAddress = input.ReadString();
            break;
          }
          case 18: {
            Captcha = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PassordModifyResponse : pb::IMessage<PassordModifyResponse> {
    private static readonly pb::MessageParser<PassordModifyResponse> _parser = new pb::MessageParser<PassordModifyResponse>(() => new PassordModifyResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PassordModifyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocolBuffer.ProtoMessageReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyResponse(PassordModifyResponse other) : this() {
      status_ = other.status_;
      mailAddress_ = other.mailAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PassordModifyResponse Clone() {
      return new PassordModifyResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "mail_address" field.</summary>
    public const int MailAddressFieldNumber = 2;
    private string mailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MailAddress {
      get { return mailAddress_; }
      set {
        mailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PassordModifyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PassordModifyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (MailAddress != other.MailAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != false) hash ^= Status.GetHashCode();
      if (MailAddress.Length != 0) hash ^= MailAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != false) {
        output.WriteRawTag(8);
        output.WriteBool(Status);
      }
      if (MailAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MailAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != false) {
        size += 1 + 1;
      }
      if (MailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MailAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PassordModifyResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      if (other.MailAddress.Length != 0) {
        MailAddress = other.MailAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadBool();
            break;
          }
          case 18: {
            MailAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
